### ISSUE TITLE
fixxxxxxxx!

### ISSUE THREAD

**Issue by ryeqb** [dr4k0nia/FlatUI-Midnight#1]
:weirdchamp:
![5m2l8](https://user-images.githubusercontent.com/31180254/85213716-4a200200-b362-11ea-90bd-d03ddeeeacce.png)

**Comment by dr4k0nia** [comment]
Fixed https://github.com/dr4k0nia/FlatUI-Midnight/commit/93803485e4de12d0a98bcc511938b460b18607d9
